-- Add MaNGA tables

DROP TABLE IF EXISTS manga_drp CASCADE;

CREATE TABLE manga_drp (
    plate           integer,
    ifudsgn         integer,
    plateifu        varchar(11) PRIMARY KEY,
    mangaid         varchar(11),
    versdrp2        varchar(6),
    versdrp3        varchar(6),
    verscore        varchar(6),
    versutil        varchar(7),
    versprim        varchar(4),
    platetyp        varchar(14),
    srvymode        varchar(14),
    objra           real,
    objdec          real,
    ifuglon         real,
    ifuglat         real,
    ifura           real,
    ifudec          real,
    ebvgal          real,
    nexp            integer,
    exptime         real,
    drp3qual        integer,
    bluesn2         real,
    redsn2          real,
    harname         varchar(35),
    frlplug         integer,
    cartid          varchar(30),
    designid        integer,
    cenra           real,
    cendec          real,
    airmsmin        real,
    airmsmed        real,
    airmsmax        real,
    seemin          real,
    seemed          real,
    seemax          real,
    transmin        real,
    transmed        real,
    transmax        real,
    mjdmin          bigint,
    mjdmed          bigint,
    mjdmax          bigint,
    gfwhm           real,
    rfwhm           real,
    ifwhm           real,
    zfwhm           real,
    mngtarg1        integer,
    mngtarg2        integer,
    mngtarg3        integer,
    catidnum        integer,
    plttarg         varchar(30),
    manga_tileid    integer,
    nsa_iauname     varchar(19),
    ifudesignsize   integer,
    ifutargetsize   integer,
    ifudesignwrongsize  integer,
    z               real,
    zmin            real,
    zmax            real,
    szmin           real,
    szmax           real,
    ezmin           real,
    ezmax           real,
    probs           real,
    pweight         real,
    psweight        real,
    psrweight       real,
    sweight         real,
    srweight        real,
    eweight         real,
    esweight        real,
    esrweight       real,
    nsa_field       integer,
    nsa_run         integer,
    nsa_camcol      integer,
    nsa_version     varchar(6),
    nsa_nsaid       integer,
    nsa_nsaid_v1b   integer,
    nsa_z           real,
    nsa_zdist       real,
    nsa_sersic_absmag_f     real,
    nsa_sersic_absmag_n     real,
    nsa_sersic_absmag_u     real,
    nsa_sersic_absmag_g     real,
    nsa_sersic_absmag_r     real,
    nsa_sersic_absmag_i     real,
    nsa_sersic_absmag_z     real,
    nsa_elpetro_absmag_f    real,
    nsa_elpetro_absmag_n    real,
    nsa_elpetro_absmag_u    real,
    nsa_elpetro_absmag_g    real,
    nsa_elpetro_absmag_r    real,
    nsa_elpetro_absmag_i    real,
    nsa_elpetro_absmag_z    real,
    nsa_elpetro_amivar_f    real,
    nsa_elpetro_amivar_n    real,
    nsa_elpetro_amivar_u    real,
    nsa_elpetro_amivar_g    real,
    nsa_elpetro_amivar_r    real,
    nsa_elpetro_amivar_i    real,
    nsa_elpetro_amivar_z    real,
    nsa_sersic_mass         real,
    nsa_elpetro_mass        real,
    nsa_elpetro_ba          real,
    nsa_elpetro_phi         real,
    nsa_extinction_f        real,
    nsa_extinction_n        real,
    nsa_extinction_u        real,
    nsa_extinction_g        real,
    nsa_extinction_r        real,
    nsa_extinction_i        real,
    nsa_extinction_z        real,
    nsa_elpetro_th50_r      real,
    nsa_petro_th50          real,
    nsa_petro_flux_f        real,
    nsa_petro_flux_n        real,
    nsa_petro_flux_u        real,
    nsa_petro_flux_g        real,
    nsa_petro_flux_r        real,
    nsa_petro_flux_i        real,
    nsa_petro_flux_z        real,
    nsa_petro_flux_ivar_f   real,
    nsa_petro_flux_ivar_n   real,
    nsa_petro_flux_ivar_u   real,
    nsa_petro_flux_ivar_g   real,
    nsa_petro_flux_ivar_r   real,
    nsa_petro_flux_ivar_i   real,
    nsa_petro_flux_ivar_z   real,
    nsa_elpetro_flux_f      real,
    nsa_elpetro_flux_n      real,
    nsa_elpetro_flux_u      real,
    nsa_elpetro_flux_g      real,
    nsa_elpetro_flux_r      real,
    nsa_elpetro_flux_i      real,
    nsa_elpetro_flux_z      real,
    nsa_elpetro_flux_ivar_f real,
    nsa_elpetro_flux_ivar_n real,
    nsa_elpetro_flux_ivar_u real,
    nsa_elpetro_flux_ivar_g real,
    nsa_elpetro_flux_ivar_r real,
    nsa_elpetro_flux_ivar_i real,
    nsa_elpetro_flux_ivar_z real,
    nsa_sersic_ba           real,
    nsa_sersic_n            real,
    nsa_sersic_phi          real,
    nsa_sersic_th50         real,
    nsa_sersic_flux_f       real,
    nsa_sersic_flux_n       real,
    nsa_sersic_flux_u       real,
    nsa_sersic_flux_g       real,
    nsa_sersic_flux_r       real,
    nsa_sersic_flux_i       real,
    nsa_sersic_flux_z       real,
    nsa_sersic_flux_ivar_f  real,
    nsa_sersic_flux_ivar_n  real,
    nsa_sersic_flux_ivar_u  real,
    nsa_sersic_flux_ivar_g  real,
    nsa_sersic_flux_ivar_r  real,
    nsa_sersic_flux_ivar_i  real,
    nsa_sersic_flux_ivar_z  real
);
\copy manga_drp FROM '../manga/drpall-v3_1_1.csv' DELIMITER ',' CSV HEADER;
-- ALTER TABLE manga_drp DROP COLUMN ind;

ANALYZE manga_drp;

-------------------------------------------------------------------------------

--DROP TABLE IF EXISTS manga_dap CASCADE;

--CREATE TABLE manga_dap (
--);
--\copy manga_drp FROM '../manga/drpall-v2_4_3.csv' DELIMITER ',' CSV HEADER;
-- ALTER TABLE manga_drp DROP COLUMN ind;

--ANALYZE manga_drp;
