export default function () {
  return {
    queryString: '',
    sesameStatus: null,
    sesameMessage: '',
    activityStream: [],
    tableStatus: null,
    tableMessage: '',
    tableData: [],
    tablePagination: {
      sortBy: 'cube_id',
      descending: false,
      page: 1,
      rowsPerPage: 30,
      rowsNumber: 0,
    },
    schema: null,
    tableList: [],
    tableColumnsObject: [],
    tableColumnsTicked: [
      'cube.cube_id',
      'cube.ra',
      'cube.dec',
      'cube.survey',
      'cube.exptime',
      'cube.manga_id',
      'cube.manga_plateifu',
      'cube.sami_catid',
      'cube.sami_cubeidpub',
      'cube.califa_id',
      'cube.califa_name',
      'cube.califa_cube',
      'cube.atlas_name',
      'sami_mgephotom_unreg.photometry',
    ],
    cubeset: [],
    pointer: null,
    currentCube: null,
    selectedSpectrum: { status: null, message: null, data: null },
  }
}
