name: IFU visualiser backend
on: push

jobs:
  test_backend:
    runs-on: ubuntu-latest

    # container:
    #   image: python:3.7

#     services:
#       postgres:
#         image: postgres
#         env:
#           POSTGRES_PASSWORD: postgres
#         ports:
#           - 5432:5432
#         options: >-
#           --health-cmd pg_isready
#           --health-interval 10s
#           --health-timeout 5s
#           --health-retries 5
#           --name db
#     steps:
#       - name: Installing q3c extension in postgres container
#         run: docker exec -t db sh -c \
#           "apt-get -qq update;
#            apt-get install -qq git make gcc postgresql-server-dev-all libssl-dev libz-dev libreadline-dev;
#            git clone https://github.com/segasai/q3c.git;
#            cd q3c;
#            make;
#            make install
#            "
      - name: Installing Postgres client (psql)
        run: |
          apt-get -qq update;
          apt-get -y install postgresql-client
    
      # - name: Install PostgreSQL dev version and client
      #   run: |
      #     apt-get update
      #     apt-get install --yes postgresql-client postgresql postgresql-contrib postgresql-server-dev-all
      # - name: Install q3c Postgres extension
      #   env:
      #     PGPASSWORD: postgres
      #   run: |
      #     git clone https://github.com/segasai/q3c.git
      #     cd q3c
      #     make
      #     make install
      #     psql -h postgres -U postgres -c 'create extension q3c;'
      #     psql -h postgres -U postgres -c 'select q3c_version();'
      - name: Testing database
        env:
          PGPASSWORD: postgres
        run: psql -h postgres -U postgres -c 'SELECT 1;'

      # - uses: actions/checkout@v2
      # - name: Install dependencies from requirements.txt
      #   run: |
      #     python -c "import sys; print(sys.version)"
      #     pip install -U pip
      #     pip install -r backend/requirements.txt
