name: IFU visualiser backend
on: push

jobs:
  test_backend:
    runs-on: ubuntu-latest

    container:
      image: python:3.7

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Install PostgreSQL dev version and client
        run: |
          apt-get update
          apt-get install --yes postgresql-client postgresql postgresql-contrib postgresql-server-dev-all
      - name: Install q3c Postgres extension
        run: |
          git clone https://github.com/segasai/q3c.git
          cd q3c
          make
          make install
          psql -h postgres -U postgres -c 'select q3c_version();'
        env:
          PGPASSWORD: postgres
      - name: Test database
        run: psql -h postgres -U postgres -c 'SELECT 1;'
        env:
          PGPASSWORD: postgres

      # - uses: actions/checkout@v2
      # - name: Install dependencies from requirements.txt
      #   run: |
      #     python -c "import sys; print(sys.version)"
      #     pip install -U pip
      #     pip install -r backend/requirements.txt
