name: IFU visualiser backend
on: push

jobs:
  test_backend:
    runs-on: ubuntu-latest

    # container:
    #   image: python:3.7

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: ifu_user
          POSTGRES_DB: ifu_db
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          --name db
    steps:
      - name: Installing q3c extension in postgres container
        run: docker exec -t db sh -c \
          "apt-get -qq update;
           apt-get install -qq git make gcc postgresql-server-dev-all libssl-dev libz-dev libreadline-dev;
           git clone https://github.com/segasai/q3c.git;
           cd q3c;
           make;
           make install
           "
      - name: Installing Postgres client (psql)
        run: |
          sudo apt-get -qq update;
          sudo apt-get -y install postgresql-client
    
      - name: Testing database
        run: psql postgresql://ifu_user:postgres@localhost:5432/ifu_db -c 'SELECT 1;'

      - name: Checking q3c extension availability
        run: psql postgresql://ifu_user:postgres@localhost:5432/ifu_db -c \
          "create extension q3c;
           select q3c_version();"
      
      - name: Checkout repo
        uses: actions/checkout@v2
  

      - name: Populate database
        run: |
          cd preparation/db
          psql postgresql://ifu_user:postgres@localhost:5432/ifu_db -c "\i upload_data.sql"
          psql postgresql://ifu_user:postgres@localhost:5432/ifu_db -c "\dt+"
          
      
      - name: Install dependencies from requirements.txt
        run: |
          python -c "import sys; print(sys.version)"
          pip install -U pip
          pip install -r backend/requirements.txt

      - name: Run api application
        run: |
          cd backend
          python manage.py makemigrations
          python manage.py migrate --noinput
          python manage.py collectstatic --noinput --link -v 2
          gunicorn website.wsgi --reload --workers 1 --bind 0.0.0.0:8000 --timeout 180 --log-level debug --access-logfile - --error-logfile - &
          curl -v 127.0.0.1:8080/api/
